// <auto-generated />
using System;
using Hpn.Modules.Appreciation.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Appreciation.Internal.Persistence.Migrations
{
    [DbContext(typeof(AppreciationDbContext))]
    [Migration("20260604143114_RedesignAppreciationTaxonomy")]
    partial class RedesignAppreciationTaxonomy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appreciation")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("Hue")
                        .HasColumnType("integer")
                        .HasColumnName("hue");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_categories_slug");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_categories_sort_order");

                    b.ToTable("appreciation_categories", "appreciation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447301"),
                            Active = true,
                            Hue = 38,
                            Label = "Physical",
                            Slug = "physical",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447302"),
                            Active = true,
                            Hue = 78,
                            Label = "Energy",
                            Slug = "energy",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447303"),
                            Active = true,
                            Hue = 350,
                            Label = "Style",
                            Slug = "style",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447304"),
                            Active = true,
                            Hue = 142,
                            Label = "Humor",
                            Slug = "humor",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447305"),
                            Active = true,
                            Hue = 264,
                            Label = "Mind",
                            Slug = "mind",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447306"),
                            Active = true,
                            Hue = 200,
                            Label = "Authentic",
                            Slug = "authentic",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid>("ReceiverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_profile_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid>("TraitId")
                        .HasColumnType("uuid")
                        .HasColumnName("trait_id");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_events");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_appreciation_events_category_id");

                    b.HasIndex("TraitId")
                        .HasDatabaseName("ix_appreciation_events_trait_id");

                    b.HasIndex("ReceiverProfileId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_appreciation_events_receiver_profile_id_created_at");

                    b.HasIndex("SenderUserId", "CreatedAt")
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_created_at");

                    b.HasIndex("SenderUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_idempotency_key");

                    b.HasIndex("SenderUserId", "ReceiverProfileId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_receiver_profile_id_cate");

                    b.ToTable("appreciation_events", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_traits");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_appreciation_traits_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_traits_slug");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_traits_sort_order");

                    b.ToTable("appreciation_traits", "appreciation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000001"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447301"),
                            Label = "Warm smile",
                            Slug = "warm_smile",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000002"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447301"),
                            Label = "Kind eyes",
                            Slug = "kind_eyes",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000003"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447301"),
                            Label = "Great hair",
                            Slug = "great_hair",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000004"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447301"),
                            Label = "Natural glow",
                            Slug = "natural_glow",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000005"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447302"),
                            Label = "Good vibe",
                            Slug = "good_vibe",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000006"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447302"),
                            Label = "Confident",
                            Slug = "confident",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000007"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447302"),
                            Label = "Calm presence",
                            Slug = "calm_presence",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000008"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447302"),
                            Label = "Magnetic",
                            Slug = "magnetic",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000009"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447303"),
                            Label = "Great fit",
                            Slug = "great_fit",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000010"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447303"),
                            Label = "Effortless",
                            Slug = "effortless",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000011"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447303"),
                            Label = "Signature look",
                            Slug = "signature_look",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000012"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447304"),
                            Label = "Made me grin",
                            Slug = "made_me_grin",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000013"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447304"),
                            Label = "Quick wit",
                            Slug = "quick_wit",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000014"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447304"),
                            Label = "Wonderfully odd",
                            Slug = "wonderfully_odd",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000015"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447305"),
                            Label = "Curious",
                            Slug = "curious",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000016"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447305"),
                            Label = "Thoughtful",
                            Slug = "thoughtful",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000017"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447305"),
                            Label = "Sharp",
                            Slug = "sharp",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000018"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447306"),
                            Label = "Genuine",
                            Slug = "genuine",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000019"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447306"),
                            Label = "Grounded",
                            Slug = "grounded",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = new Guid("2a1d7f00-0000-4000-8000-000000000020"),
                            Active = true,
                            CategoryId = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447306"),
                            Label = "True to themselves",
                            Slug = "true_to_themselves",
                            SortOrder = 20
                        });
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.GivenAppreciationStat", b =>
                {
                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("SenderUserId", "CategoryId")
                        .HasName("pk_given_appreciation_stats");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_given_appreciation_stats_category_id");

                    b.ToTable("given_appreciation_stats", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.ReceivedAppreciationStat", b =>
                {
                    b.Property<Guid>("ReceiverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_profile_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("LastAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_at");

                    b.HasKey("ReceiverProfileId", "CategoryId")
                        .HasName("pk_received_appreciation_stats");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_received_appreciation_stats_category_id");

                    b.ToTable("received_appreciation_stats", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationEvent", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appreciation_events_appreciation_categories_category_id");

                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationTrait", null)
                        .WithMany()
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appreciation_events_appreciation_traits_trait_id");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationTrait", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appreciation_traits_appreciation_categories_category_id");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.GivenAppreciationStat", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_given_appreciation_stats_appreciation_categories_category_id");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.ReceivedAppreciationStat", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_received_appreciation_stats_appreciation_categories_categor");
                });
#pragma warning restore 612, 618
        }
    }
}
