// <auto-generated />
using System;
using Hpn.Modules.Appreciation.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Appreciation.Internal.Persistence.Migrations
{
    [DbContext(typeof(AppreciationDbContext))]
    [Migration("20260601194118_AddAppreciationSubmission")]
    partial class AddAppreciationSubmission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appreciation")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_categories_slug");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_categories_sort_order");

                    b.ToTable("appreciation_categories", "appreciation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447201"),
                            Active = true,
                            Label = "Warm smile",
                            Slug = "warm_smile",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447202"),
                            Active = true,
                            Label = "Authentic",
                            Slug = "authentic",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447203"),
                            Active = true,
                            Label = "Stylish",
                            Slug = "stylish",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447204"),
                            Active = true,
                            Label = "Calming energy",
                            Slug = "calming_energy",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447205"),
                            Active = true,
                            Label = "Confident",
                            Slug = "confident",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447206"),
                            Active = true,
                            Label = "Expressive",
                            Slug = "expressive",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447207"),
                            Active = true,
                            Label = "Fun energy",
                            Slug = "fun_energy",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447208"),
                            Active = true,
                            Label = "Elegant",
                            Slug = "elegant",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447209"),
                            Active = true,
                            Label = "Trustworthy",
                            Slug = "trustworthy",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447210"),
                            Active = true,
                            Label = "Creative",
                            Slug = "creative",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447211"),
                            Active = true,
                            Label = "Kind",
                            Slug = "kind",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("0f93fb39-2e34-4c90-bf9d-28df31447212"),
                            Active = true,
                            Label = "Intelligent-looking",
                            Slug = "intelligent",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid>("ReceiverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_profile_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_events");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_appreciation_events_category_id");

                    b.HasIndex("ReceiverProfileId")
                        .HasDatabaseName("ix_appreciation_events_receiver_profile_id");

                    b.HasIndex("SenderUserId", "CreatedAt")
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_created_at");

                    b.HasIndex("SenderUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_idempotency_key");

                    b.HasIndex("SenderUserId", "ReceiverProfileId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_receiver_profile_id_cate");

                    b.ToTable("appreciation_events", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.GivenAppreciationStat", b =>
                {
                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("SenderUserId", "CategoryId")
                        .HasName("pk_given_appreciation_stats");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_given_appreciation_stats_category_id");

                    b.ToTable("given_appreciation_stats", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.ReceivedAppreciationStat", b =>
                {
                    b.Property<Guid>("ReceiverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_profile_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("LastAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_at");

                    b.HasKey("ReceiverProfileId", "CategoryId")
                        .HasName("pk_received_appreciation_stats");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_received_appreciation_stats_category_id");

                    b.ToTable("received_appreciation_stats", "appreciation");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationEvent", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appreciation_events_appreciation_categories_category_id");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.GivenAppreciationStat", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_given_appreciation_stats_appreciation_categories_category_id");
                });

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.ReceivedAppreciationStat", b =>
                {
                    b.HasOne("Hpn.Modules.Appreciation.Internal.Domain.AppreciationCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_received_appreciation_stats_appreciation_categories_categor");
                });
#pragma warning restore 612, 618
        }
    }
}
