// <auto-generated />
using System;
using Hpn.Modules.Appreciation.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Appreciation.Internal.Persistence.Migrations
{
    [DbContext(typeof(AppreciationDbContext))]
    partial class AppreciationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appreciation")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Appreciation.Internal.Domain.AppreciationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<Guid>("ReceiverProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_profile_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_appreciation_events");

                    b.HasIndex("ReceiverProfileId")
                        .HasDatabaseName("ix_appreciation_events_receiver_profile_id");

                    b.HasIndex("SenderUserId", "CreatedAt")
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_created_at");

                    b.HasIndex("SenderUserId", "ReceiverProfileId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_appreciation_events_sender_user_id_receiver_profile_id_cate");

                    b.ToTable("appreciation_events", "appreciation");
                });
#pragma warning restore 612, 618
        }
    }
}
