// <auto-generated />
using System;
using Hpn.Modules.Moderation.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Moderation.Internal.Persistence.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    [Migration("20260602142153_InitialModeration")]
    partial class InitialModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("moderation")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Moderation.Internal.Domain.AccountTrust", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<double>("Score")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("score");

                    b.Property<string>("Signals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("signals");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_account_trust");

                    b.ToTable("account_trust", "moderation");
                });

            modelBuilder.Entity("Hpn.Modules.Moderation.Internal.Domain.ModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_moderation_actions");

                    b.HasIndex("TargetUserId", "CreatedAt")
                        .HasDatabaseName("ix_moderation_actions_target_user_id_created_at");

                    b.ToTable("moderation_actions", "moderation");
                });

            modelBuilder.Entity("Hpn.Modules.Moderation.Internal.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_profile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("TargetProfileId", "CreatedAt")
                        .HasDatabaseName("ix_reports_target_profile_id_created_at");

                    b.HasIndex("TargetProfileId", "Status")
                        .HasDatabaseName("ix_reports_target_profile_id_status");

                    b.HasIndex("ReporterUserId", "TargetProfileId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_reporter_user_id_target_profile_id_type");

                    b.ToTable("reports", "moderation");
                });
#pragma warning restore 612, 618
        }
    }
}
