// <auto-generated />
using System;
using Hpn.Modules.SocialFingerprint.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.SocialFingerprint.Internal.Persistence.Migrations
{
    [DbContext(typeof(SocialFingerprintDbContext))]
    partial class SocialFingerprintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("social_fingerprint")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.SocialFingerprint.Internal.Domain.SocialFingerprintSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Distribution")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("distribution");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("sample_size");

                    b.Property<string>("TopTraits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_traits");

                    b.HasKey("Id")
                        .HasName("pk_social_fingerprint_snapshots");

                    b.HasIndex("ProfileId", "PeriodStart")
                        .HasDatabaseName("ix_social_fingerprint_snapshots_profile_id_period_start");

                    b.HasIndex("ProfileId", "Period", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_social_fingerprint_snapshots_profile_id_period_period_start");

                    b.ToTable("social_fingerprint_snapshots", "social_fingerprint");
                });
#pragma warning restore 612, 618
        }
    }
}
