// <auto-generated />
using System;
using Hpn.Modules.Profile.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Profile.Internal.Persistence.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260601154650_AddProfileVerification")]
    partial class AddProfileVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_interests");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_interests_slug");

                    b.ToTable("interests", "profile");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10001"),
                            Label = "Books",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10002"),
                            Label = "Music",
                            Slug = "music"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10003"),
                            Label = "Art",
                            Slug = "art"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10004"),
                            Label = "Food",
                            Slug = "food"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10005"),
                            Label = "Nature",
                            Slug = "nature"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10006"),
                            Label = "Travel",
                            Slug = "travel"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10007"),
                            Label = "Movement",
                            Slug = "movement"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10008"),
                            Label = "Film",
                            Slug = "film"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a10009"),
                            Label = "Technology",
                            Slug = "technology"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a1000a"),
                            Label = "Learning",
                            Slug = "learning"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a1000b"),
                            Label = "Volunteering",
                            Slug = "volunteering"
                        },
                        new
                        {
                            Id = new Guid("018f0b65-2c2a-7a10-9d4d-47b6f6a1000c"),
                            Label = "Craft",
                            Slug = "craft"
                        });
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.ProfileInterest", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid")
                        .HasColumnName("interest_id");

                    b.HasKey("ProfileId", "InterestId")
                        .HasName("pk_profile_interests");

                    b.HasIndex("InterestId")
                        .HasDatabaseName("ix_profile_interests_interest_id");

                    b.ToTable("profile_interests", "profile");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.UserBlock", b =>
                {
                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_user_id");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("BlockerUserId", "BlockedUserId")
                        .HasName("pk_user_blocks");

                    b.ToTable("user_blocks", "profile");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("SelfDescribeText")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("self_describe_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", "profile");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.VisibilityPreferences", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<bool>("HideFromCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hide_from_country");

                    b.Property<int?>("MinDistanceKm")
                        .HasColumnType("integer")
                        .HasColumnName("min_distance_km");

                    b.Property<bool>("Paused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paused");

                    b.Property<bool>("ShowOnlyOutsideCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_only_outside_country");

                    b.Property<bool>("VerifiedOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verified_only");

                    b.Property<bool>("WomenForWomen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("women_for_women");

                    b.HasKey("ProfileId")
                        .HasName("pk_visibility_preferences");

                    b.ToTable("visibility_preferences", "profile");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.ProfileInterest", b =>
                {
                    b.HasOne("Hpn.Modules.Profile.Internal.Domain.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_interests_interests_interest_id");

                    b.HasOne("Hpn.Modules.Profile.Internal.Domain.UserProfile", null)
                        .WithMany("ProfileInterests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_interests_profiles_profile_id");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.VisibilityPreferences", b =>
                {
                    b.HasOne("Hpn.Modules.Profile.Internal.Domain.UserProfile", null)
                        .WithOne("VisibilityPreferences")
                        .HasForeignKey("Hpn.Modules.Profile.Internal.Domain.VisibilityPreferences", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visibility_preferences_profiles_profile_id");
                });

            modelBuilder.Entity("Hpn.Modules.Profile.Internal.Domain.UserProfile", b =>
                {
                    b.Navigation("ProfileInterests");

                    b.Navigation("VisibilityPreferences")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
