// <auto-generated />
using System;
using Hpn.Modules.Admin.Internal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hpn.Modules.Admin.Internal.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260602154749_AddAdminAuditLog")]
    partial class AddAdminAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hpn.Modules.Admin.Internal.Domain.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("TargetRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_ref");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_log");

                    b.HasIndex("AdminUserId", "CreatedAt")
                        .HasDatabaseName("ix_admin_audit_log_admin_user_id_created_at");

                    b.HasIndex("TargetRef", "CreatedAt")
                        .HasDatabaseName("ix_admin_audit_log_target_ref_created_at");

                    b.ToTable("admin_audit_log", "admin");
                });

            modelBuilder.Entity("Hpn.Modules.Admin.Internal.ReadModel.AdminQueueItemReadModel", b =>
                {
                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("LatestReportAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("latest_report_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_status");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("report_count");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<double>("TrustScore")
                        .HasColumnType("double precision")
                        .HasColumnName("trust_score");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Hpn.Modules.Admin.Internal.ReadModel.AdminReportReadModel", b =>
                {
                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("target_display_name");

                    b.Property<Guid>("TargetProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_profile_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Hpn.Modules.Admin.Internal.ReadModel.AdminStatsReadModel", b =>
                {
                    b.Property<int>("ActionedReports")
                        .HasColumnType("integer")
                        .HasColumnName("actioned_reports");

                    b.Property<double>("AverageTrustScore")
                        .HasColumnType("double precision")
                        .HasColumnName("average_trust_score");

                    b.Property<int>("CurrentlyBanned")
                        .HasColumnType("integer")
                        .HasColumnName("currently_banned");

                    b.Property<int>("CurrentlyRestricted")
                        .HasColumnType("integer")
                        .HasColumnName("currently_restricted");

                    b.Property<int>("DismissedReports")
                        .HasColumnType("integer")
                        .HasColumnName("dismissed_reports");

                    b.Property<int>("OpenReports")
                        .HasColumnType("integer")
                        .HasColumnName("open_reports");

                    b.Property<int>("ReviewingReports")
                        .HasColumnType("integer")
                        .HasColumnName("reviewing_reports");

                    b.Property<int>("VerifiedProfiles")
                        .HasColumnType("integer")
                        .HasColumnName("verified_profiles");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
